### ISSUE TITLE
Some sides of blocks are transparent

### ISSUE THREAD

**Issue by traveldesign** [SaymN/VanillaThings#19] opened 2020-03-24 20:56 UTC
Sometimes when I place down blocks I can see through all the way to the sky on one of the block's sides. If you'd like a screenshot I can get one for you.

**Comment by jon-bartus** [comment] 2020-03-24 22:22
Is this on adjacent Stairs in different orientations, or slabs that are next to each other? If so, this is probably a duplicate of either #15 or #16 which have screenshots.

**Comment by traveldesign** [comment] 2020-04-27 21:59
Yes, it's like #16. Except I could see all the way through the ground to the skybox below if that makes sense

**Comment by SaymN** [comment] 2020-08-19 20:12
Fixed in Ver. 0.6

**Closed by SaymN** 2020-08-19 20:12 UTC
